version: '3.8'

# =============================================================================
# MINIMAL WEBHOOK ARCHITECTURE - NO PYTHON
# Nutzt Telegram Webhooks + bash Scripts + curl
# =============================================================================

services:
  # nginx + bash CGI für Webhook Empfang
  webhook-gateway:
    image: nginx:alpine
    container_name: webhook-gateway
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - ./webhook-scripts:/usr/share/nginx/html/webhook
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      - webhook-network

  # Redis für Message Queue
  redis:
    image: redis:7-alpine
    container_name: webhook-redis
    restart: unless-stopped
    volumes:
      - redis_data:/data
    networks:
      - webhook-network

  # Signal Processor (bash + curl)
  signal-processor:
    image: alpine:latest
    container_name: signal-processor
    restart: unless-stopped
    environment:
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - OWN_GROUP_CHAT_ID=${OWN_GROUP_CHAT_ID}
      - REDIS_HOST=redis
    volumes:
      - ./signal-scripts:/app
    working_dir: /app
    command: /app/signal_processor.sh
    depends_on:
      - redis
    networks:
      - webhook-network
    # Installiert redis-cli und curl
    entrypoint: |
      sh -c "
        apk add --no-cache redis curl jq bash &&
        exec /app/signal_processor.sh
      "

networks:
  webhook-network:
    driver: bridge

volumes:
  redis_data:
    driver: local