version: '3.8'
services:
  db:
    image: postgres:15
    container_name: trading-bot-db
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-change-me-in-production}
      POSTGRES_DB: ${POSTGRES_DB:-trading_bot}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-postgres}"]
      interval: 10s
      timeout: 5s
      retries: 5
  
  bot:
    build: .
    container_name: trading-bot-app
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8080:8080"
      - "9090:9090"
    environment:
      - DATABASE_URL=postgresql+asyncpg://${POSTGRES_USER:-postgres}:${POSTGRES_PASSWORD:-change-me-in-production}@db:5432/${POSTGRES_DB:-trading_bot}
      - TRADING_ENABLED=false
      - BINGX_TESTNET=true
      - LOG_LEVEL=INFO
      # Add your secrets to .env file
      - TELEGRAM_API_ID=${TELEGRAM_API_ID}
      - TELEGRAM_API_HASH=${TELEGRAM_API_HASH}
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - BINGX_API_KEY=${BINGX_API_KEY}
      - BINGX_SECRET_KEY=${BINGX_SECRET_KEY}
    volumes:
      - ./src:/app/src:ro
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  postgres_data: